platform :ios, "11.2"
use_modular_headers!

project 'BlockChainWallet.xcodeproj'
target 'BlockChainWallet' do
  
  pod 'TokenCore', :path => '../'
  pod 'PureLayout'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Alamofire', '~> 5.0.0-beta.2'
  pod "CoreBitcoin", git: "https://github.com/consenlabs/token-core-ios-dep.git"
  pod 'SnapKit', '~> 5.0.0'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'IQKeyboardManagerSwift'
  pod 'SQLite.swift', '~> 0.12.0'
  pod 'HandyJSON', '~> 5.0.2'
  pod 'MJRefresh', '~> 3.5.0'

#  pod "TokenCore", git: "https://github.com/consenlabs/token-core-ios.git"
end

